server:
  port: 8090
  servlet:
    context-path: /${spring.application.name}

spring:
  datasource:
    url: ${DB_MULTIPOS_URL}
    username: ${DB_MULTIPOS_USER}
    password: ${DB_MULTIPOS_PSWD}
    driver-class-name: org.postgresql.Driver
  application:
    name: ms-organization
  jpa:
    hibernate:
      ddl-auto: update